version: '3.6'

services:
  mlapi:
    build:
      context: .
      dockerfile: ./Dockerfile
#    image: ghcr.io/baudneo/mlapi_cudnn-base:latest
    container_name: mlapi
    restart: always
    # Need privileged for USB TPU access, comment out if not using TPU
    privileged: true
    ports:
      - "5000:5000"
    networks:
      - zoneminder
    volumes:
      - ./mlapi/config:/config
      - ./mlapi/log:/log
      # TPU access (mount the whole USB system)
      - /dev/bus/usb:/dev/bus/usb
#      You can upgrade mlapi by replacing mlapi.py with a newer version. mlapi.py is the only file inside
#      the containers /mlapi dir. Make sure you place a current or newer mlapi.py inside of ./mlapi/upgrade
      - ./mlapi/upgrade:/mlapi

# ADVANCED! To enable upgrading neo-pyzm, it takes a bit more work. Find the neo-pyzm folder in the python library.
# using docker exec -it <container name> /usr/bin/bash (or /bin/bash) and look around for the /usr/local/lib/python3.X/dist-packages/neo-pyzm* folder.
# Clone the new Neo pyzm repo and copy the nested pyzm folder in a volume mapped to where pyzm is installed so the file structure matches, pyzm is now upgraded to the latest release/commit..
    env_file:
      - ./.env
    # NVIDIA GPU Example - https://docs.docker.com/compose/gpu-support/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu, compute, utility ]
    environment:
      - - PYZM_CONF=/config
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video

  db:
    container_name: db
    image: mariadb
    restart: always
    networks:
      - zoneminder
    volumes:
      - ./zm/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=zm
    env_file:
      - ./.env

  zoneminder:
    container_name: zoneminder
#    image: ghcr.io/baudneo/eventserver-mlapi:latest
    image: eventserver-mlapi:latest
    restart: always
    stop_grace_period: 45s
    depends_on:
      - db
    ports:
      - 80:80
      - 443:443
      - 9000:9000
    networks:
      - zoneminder
    volumes:
      - ./zm/data:/data
      - ./zm/config:/config
      - ./zm/log:/log
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 1000000000
    env_file:
      - ./.env
#    environment:
#      - ZM_SERVER_HOST=zoneminder1



networks:
  zoneminder: