version: '3.6'

services:
  mlapi:
#    build:
#      context: .
#      dockerfile: ./Dockerfile
    image: ghcr.io/baudneo/mlapi_cudnn-base:0.0.3
#    image: mlapi_new:testing
    container_name: mlapi
    restart: always
    # Need privileged for USB TPU access, comment out if not using TPU
    privileged: true
    ports:
      - "5000:5000"
    networks:
      - zoneminder
    extra_hosts:
      - "zm.baudneo.com:10.0.0.30"
    volumes:
      - ./mlapi/config:/config
      - ./mlapi/log:/log
#      - ./mlapi/mlapi.py:/mlapi/mlapi.py
#      - ./pyzm:/usr/local/lib/python3.8/dist-packages/pyzm/
      # TPU access (mount the whole USB system)
      - /dev/bus/usb:/dev/bus/usb
#      You can upgrade mlapi by replacing mlapi.py with a newer version. mlapi.py is the only file inside
#      the containers /mlapi dir. Make sure you place a current or newer mlapi.py inside of ./mlapi/upgrade
#      - ./mlapi/upgrade:/mlapi
# ADVANCED! To enable upgrading neo-pyzm, it takes a bit more work. Find the neo-pyzm folder in the python library.
# using docker exec -it <container name> /usr/bin/bash (or /bin/bash) and look around for the /usr/local/lib/python3.X/dist-packages/neo-pyzm* folder.
# Clone the new Neo pyzm repo and copy the nested pyzm folder in a volume mapped to where pyzm is installed so the file structure matches, pyzm is now upgraded to the latest release/commit..
    env_file:
      - ./.env
    # NVIDIA GPU Example - https://docs.docker.com/compose/gpu-support/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu, compute, utility ]



networks:
  zoneminder:
