#!/usr/bin/with-contenv bash
# shellcheck shell=bash
. "/usr/local/bin/logger"
# ==============================================================================
# Neo MLAPI
# ==============================================================================
pkill -2 -f "/python3 -m /mlapi/mlapi.py --config /config/mlapi/mlapiconfig.yml"
s6-svscanctl -t /var/run/s6/services
