#!/usr/bin/with-contenv bash
# shellcheck shell=bash
#. "/usr/local/bin/logger"
# ==============================================================================
# MLAPI
# Runs MLAPI
# ==============================================================================


MLAPI_FLAGS=(--config /config/mlapiconfig.yml --from-docker)

if [ "${MLAPI_DEBUG_ENABLED}" -eq 1 ]; then
  echo "Enabling MLAPI Debug!" | info
  MLAPI_FLAGS+=("--debug")
fi

echo "Starting Neo MLAPI..." | info
s6-setuidgid www-data python3 /mlapi/mlapi.py "${MLAPI_FLAGS[@]}"
# Notify s6 service is up
fdmove 1 3 printf "done\n"
