#!/usr/bin/with-contenv bash
# shellcheck shell=bash
#. "/usr/local/bin/logger"
# ==============================================================================
# MLAPI
# Runs MLAPI
# ==============================================================================


MLAPI_FLAGS=(--config /config/mlapiconfig.yml --from-docker)

if [ "${MLAPI_DEBUG_ENABLED}" -eq 1 ]; then
  echo "Enabling MLAPI Debug!"
  MLAPI_FLAGS+=("--debug")
fi

echo "Starting Neo MLAPI with FLAGS: ${MLAPI_FLAGS[*]}"
s6-setuidgid www-data python3 /mlapi/mlapi.py "${MLAPI_FLAGS[@]}" 2>&1
